extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
  document-start: disable
  comments:
    min-spaces-from-content: 1

ignore:
  - .venv/
  - build/
  - dist/
